// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZeissEmpMgmt.Context;

namespace ZeissEmpMgmt.Migrations
{
    [DbContext(typeof(EmpContext))]
    [Migration("20220324193425_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ZeissEmpMgmt.Model.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Infra"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Facilities"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Security"
                        });
                });

            modelBuilder.Entity("ZeissEmpMgmt.Model.Employee", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("EmpId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RoleId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmpId = 1,
                            CreatedAt = new DateTime(2022, 3, 25, 1, 4, 13, 913, DateTimeKind.Local).AddTicks(297),
                            DepartmentId = 1,
                            FirstName = "Shailesh",
                            LastName = "Dayani",
                            RoleId = 2
                        },
                        new
                        {
                            EmpId = 2,
                            CreatedAt = new DateTime(2022, 3, 25, 1, 4, 13, 914, DateTimeKind.Local).AddTicks(2126),
                            DepartmentId = 1,
                            FirstName = "Fname1",
                            LastName = "LName1",
                            RoleId = 3
                        },
                        new
                        {
                            EmpId = 3,
                            CreatedAt = new DateTime(2022, 3, 25, 1, 4, 13, 914, DateTimeKind.Local).AddTicks(2189),
                            DepartmentId = 3,
                            FirstName = "Shailesh",
                            LastName = "Dayani",
                            RoleId = 4
                        },
                        new
                        {
                            EmpId = 4,
                            CreatedAt = new DateTime(2022, 3, 25, 1, 4, 13, 914, DateTimeKind.Local).AddTicks(2192),
                            DepartmentId = 4,
                            FirstName = "FName2",
                            LastName = "LName2",
                            RoleId = 1
                        },
                        new
                        {
                            EmpId = 5,
                            CreatedAt = new DateTime(2022, 3, 25, 1, 4, 13, 914, DateTimeKind.Local).AddTicks(2194),
                            DepartmentId = 1,
                            FirstName = "FName3",
                            LastName = "LName3",
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("ZeissEmpMgmt.Model.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Developer"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Scrum Master"
                        },
                        new
                        {
                            Id = 4,
                            Name = "QA"
                        });
                });

            modelBuilder.Entity("ZeissEmpMgmt.Model.Employee", b =>
                {
                    b.HasOne("ZeissEmpMgmt.Model.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZeissEmpMgmt.Model.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
